server:
  port: 8081
spring:
  application:
    name: inventory
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      database: inventory
      password: rootpass
      port: 30001
      host: localhost
