server:
  port: 8084
spring:
  application:
    name: hr
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      database: employees
      password: rootpass
      port: 30001
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka